config/routes.rb
Rails.application.routes.draw do
  resources :interventions
  devise_for :users
  
  resources :quotes
  resources :leads
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Authenticates Blazer Using Devise
  authenticate :user, ->(user) { user.superadmin_role? } do
    mount Blazer::Engine, at: "blazer"
  end
 # Authenticates Blazer Using Devise
 authenticate :user, ->(user) { user.superadmin_role? or user.employee_role?} do
  get 'intervention' => 'pages#intervention'
end

  # # If Above Doesn't Work Then Uncomment Below:
  # mount Blazer::Engine, at: "blazer"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#index"
  get "residential" => "pages#residential"
  get "commercial" => "pages#commercial"
  get "quotes" => "pages#quote"
  # get 'intervention' => 'pages#intervention'

  get "/index" => "pages#index"

  # /quotes is the action from the form in quote.html.erb
  post "/quotes" => "quotes#create"
  # post 'newIntervention', to: "interventions#newIntervention"
  # /leads is the action from the form in index.html.erb
  post "/leads" => "leads#create"

  # match '/watson'     => 'watson#speak', via: :get
  get '/watson/update' => 'watson#speak'
 
   
end

app/models/intervention.rb
class Intervention < ApplicationRecord
    belongs_to :customer
    belongs_to :building
    belongs_to :battery, optional: true
    belongs_to :column, optional: true
    belongs_to :elevator, optional: true
    belongs_to :employee, optional: true
    belongs_to :author, class_name: "Employee"


#     def create_intervention_ticket
#         client = ZendeskAPI::Client.new do |config|
#             config.url = ENV['ZENDESK_URL']
#             config.username = ENV['ZENDESK_USERNAME']
#             config.token = ENV['ZENDESK_TOKEN']
#         end

# # var cl = Customer.find(self.customer_id).company_name

#         ZendeskAPI::Ticket.create!($client, 
#             :subject => "New intervention request!", 
#             :comment => { 
#                 :value => "New intervention created by employee ID: #{self.employee},

                
#                 Customer ID: #{self.customer_id}
#                 Building ID: #{self.building_id}
#                 Battery ID: #{self.battery_id}
#                 Column ID: #{self.column_id}
#                 Elevator ID: #{self.elevator_id}
#                 Assigned to employee ID: #{self.employee_id}
#                 Description: #{self.report} "
#             }, 
#             :requester => { 
#                 "name": Employee.where(user_id: self.employee).first.first_name + " " + Employee.where(user_id: self.employee).first.last_name, 
#                 "email": Employee.where(user_id: self.employee).first.email
#             },
#             :priority => "normal",
#             :type => "problem"
#             )
#         end

end
# Customer.find

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
  before_action :set_intervention, only: [:show, :edit, :update, :destroy]
  before_action :is_employee? #method for check is the current user is a employee


  # GET /interventions
  # GET /interventions.json
  def index
    @interventions = Intervention.all
  end

  # GET /interventions/1
  # GET /interventions/1.json
  def show
  end

  # GET /interventions/new
  def new
    @intervention = Intervention.new
  end
  
  # GET /interventions/1/edit
  def edit
  end
  
  # POST /interventions
  # POST /interventions.json
  def create
   
    @intervention = Intervention.new(intervention_params)

    # Get format name of employee connected
    employee = current_user.employee.full_name

    # Give the id of the employee connected
    @intervention.author_id = current_user.employee.id

    # Data get for zendesk ticket
    battery_id = @intervention.battery_id
    column_id = @intervention.column_id
    elevator_id = @intervention.elevator_id

    # Condition for null ids not required
    if @intervention.elevator_id
      @intervention.battery_id = nil
      @intervention.column_id = nil
    elsif @intervention.column_id
      @intervention.battery_id = nil
    end

    if @intervention.save!
      helpers.ticket_intervention(@intervention, employee, battery_id, column_id, elevator_id)
      

      respond_to do |format|
    
        format.html { render :show, status: :created, location: @intervention }
        # format.json { render json: @intervention, status: :created }

      end
      # redirect_to '/interventions/new', notice: 'Intervention was successfully created.' 
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interventions/1
  # PATCH/PUT /interventions/1.json
  def update
    respond_to do |format|
      if @intervention.update(intervention_params)
        format.html { redirect_to @intervention, notice: 'Intervention was successfully updated.' }
        format.json { render :show, status: :ok, location: @intervention }
      else
        format.html { render :edit }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interventions/1
  # DELETE /interventions/1.json
  def destroy
    @intervention.destroy
    respond_to do |format|
      format.html { redirect_to interventions_url, notice: 'Intervention was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_intervention
    @intervention = Intervention.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def intervention_params
    params.permit(
        :customer_id,
        :building_id,
        :battery_id,
        :column_id,
        :elevator_id,
        :employee_id,
        :start_date_intervention,
        :end_date_intervention,
        :result,
        :report,
        :status,
        :author_id)
  end
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/_form.html.erb
            <!-- PAGE HEADER -->
                <section class="section-sm alternate">
                    <div class="overlay dark-4"></div>
                    <br>
                    <br>
            <h2 class="text-center">Request an Intervention</h2>
                </section>
            <!-- /PAGE HEADER -->


        <%= form_tag @intervention do %>

            
            <div class="row">
                <div class="col-md-4 text-center selcust">
                    <label for="customer_id">Customer*</label>
                    <select id="customer_id" class="form-control pointer" name="customer_id" required>
                    </select>
                </div>
                <div class="col-md-2 text-center selbuild selform">
                    <label for="building_id">Building*</label>
                    <select id="building_id" class="form-control pointer" name="building_id" required>
                    </select>
                </div>
                <div class="col-md-2 text-center selbatt selform">
                    <label for="battery_id">Battery*</label>
                    <select id="battery_id" class="form-control pointer" name="battery_id" required>
                    </select>
                </div>
                <div class="col-md-2 text-center selcol selform">
                    <label for="column_id">Column*</label>
                    <select id="column_id" class="form-control pointer" name="column_id">
                    <option value="">None</option>
                    </select>
                </div>
                <div class="col-md-2 text-center selelev selform">
                    <label for="elevator_id">Elevator*</label>
                    <select id="elevator_id" class="form-control pointer" name="elevator_id">
                    <option value="">None</option>
                    </select>
                </div>
            </div>
            <div class="row">

                <div class="col-md-4 text-center selemp">
                    <label for="employee_id">Assign to:</label>
                    <select id="employee_id" class="form-control pointer" name="employee_id">
                        <option value="">None</option>
                    </select>
                </div>

                <div class="col-md-8 text-center seldesc">
                    <label for="report">Description</label>
                    <input type="text" placeholder="Description here" id="report" class="form-control pointer" name="report">
                </div>
                <br \>
                <br \>
            </div>
            </h4>
            	
            <div class="row">
                <div class="col-md-12 text-center">
                    <button type="submit" class="btn btn-danger btn-lg btn-red btn-block">Send</button>
                </div>      
            </div>
        <% end %>

        <script>

        // Creating a Dropdown list for the Customers (Required Field) 
        function customer_Dropdown() {
            $("#customer_id").append("<option disabled selected>--Required--</option>")
            <% Customer.all.each do |customer| %>
                $("#customer_id").append("<option value='<%=customer.id%>'><%=customer.company_name%></option>")
            <% end %>
        };

        // Creating a Dropdown list for the Employees 
        function employee_Dropdown() {
            $("#employee_id").append("<option value='' selected>None</option>")
            <% Employee.all.each do |employee| %>
                $("#employee_id").append("<option value='<%=employee.id%>'><%=employee.first_name%> <%=employee.last_name%></option>")
            <% end %>
        };

        // Creating a Dropdown list for the Buildings (Required Field)
        function buildingDropdown() {
            $("#building_id").append("<option disabled selected>--Required--</option>")
            <% Building.all.each do |building| %>
            if ($('#customer_id').val() == <%=building.customer_id%>){
                $("#building_id").append("<option value='<%=building.id%>'><%=building.id%></option>")
            }
            <% end %>
        };

        // Creating a Dropdown list for the Batteries (Required Field)
        function batteryDropdown() {
            $("#battery_id").append("<option disabled selected>--Required--</option>")
            <% Battery.all.each do |battery| %>
            if ($('#building_id').val() == <%=battery.building_id%>){
                $("#battery_id").append("<option value='<%=battery.id%>'>Battery #<%=battery.id%></option>")
            }
            <% end %>
        };

        // Creating a Dropdown list for the Columns (Required Field)
        function columnDropdown() {
            $("#column_id").append("<option value='' selected>None</option>")
            <% Column.all.each do |column| %>
            if ($('#battery_id').val() == <%=column.battery_id%>){
                $("#column_id").append("<option value='<%=column.id%>'>Column #<%=column.id%></option>")
            }
            <% end %>
        };

        // Creating a Dropdown list for the Elevators (Required Field) 
        function elevatorDropdown() {
            $("#elevator_id").append("<option value='' selected>None</option>")
            <% Elevator.all.each do |elevator| %>
            if ($('#column_id').val() == <%=elevator.column_id%>){
                $("#elevator_id").append("<option value='<%=elevator.id%>'>Elevator  #<%=elevator.id%></option>")
            }
            <% end %>
        };

        // functions to remove pre-populated fields

        function autoRemove(opt) {
            $(opt).find('option').remove()
        };

        function autoRemoveAll() {
            $('#intervention').find('option').remove()

        };
        function clearText() {
                $('#report').val("")
            }

        // Invoking the functions to restart the fields after reloading the page.
        autoRemoveAll()
        clearText()
        customer_Dropdown()
        employee_Dropdown()

        $(".selform").hide()

        // Event listeners that manipulate the select fields
        $('#customer_id').change(function(){
            autoRemove('#building_id')
            autoRemove('#battery_id')
            autoRemove('#column_id')
            autoRemove('#elevator_id')
            $(".selform").hide()
            $(".selbuild").show()
            buildingDropdown()
        });

        $('#building_id').change(function(){
            autoRemove('#battery_id')
            autoRemove('#column_id')
            autoRemove('#elevator_id')
            $(".selcol").hide()
            $(".selelev").hide()
            $(".selbatt").show()
            batteryDropdown()
        });

        $('#battery_id').change(function(){
            autoRemove('#column_id')
            autoRemove('#elevator_id')
            $(".selelev").hide()
            $(".selcol").show()
            columnDropdown()
        });

        $('#column_id').change(function(){
            autoRemove('#elevator_id')
            $(".selelev").show()
            elevatorDropdown()
        });

        </script>

app/views/interventions/_form.html.test.erb
<div class="container">
  <%= form_for @intervention do |f| %>
    <div class="row">
      <div class="col-6 form-group">
        <div class="field">
          <%= f.label :customer_id %>
          <%= f.collection_select :customer_id, Customer.order(:company_name), :id, :company_name,{}, {:include_blank => "Select a customer", :required => true} %>
        </div>
        <div class="field">
          <%= f.label :building_id %>
          <%= f.grouped_collection_select :building_id, Customer.order(:id), :buildings, :company_name, :id, :loc_building, {}, {:required => true} %>
        </div>
        <div class="field">
          <%= f.label :battery_id %>
          <%= f.grouped_collection_select :battery_id, Building.order(:id), :batteries, :loc_building, :id, :b_format_form %>
        </div>
        <div class="field">
          <%= f.label :column_id %>
          <%= f.grouped_collection_select :column_id, Battery.order(:id), :columns, :b_format_form, :id, :id %>
        </div>
        <div class="field">
          <%= f.label :elevator_id %>
          <%= f.grouped_collection_select :elevator_id, Column.order(:id), :elevators, :id, :id, :e_format_form %>
        </div>

      </div>
      <div class="col-6 form-group">
        <%= f.label :employee_id %>
        <%= f.collection_select :employee_id, Employee.order(:first_name), :id, :full_name, :include_blank => "Select a employee" %>

        <%= f.label :report %>
        <%= f.text_area :report, :required => true %>

      </div>
    </div>
    <div class="row">
      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
    </div>

  <% end %>

app/views/interventions/edit.html.erb
<h1>Editing Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Show', @intervention %> |
<%= link_to 'Back', interventions_path %>

app/views/interventions/index.html.erb
            <!-- PAGE HEADER -->
                <section class="section-sm alternate">
                    <div class="overlay dark-4"></div>
                    <br>
                    <br>
            <h2 class="text-center">Intervention</h2>
                </section>
            <!-- /PAGE HEADER -->
<p id="notice"><%= notice %></p>

<h1>Intervention</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Customer</th>
      <th>Building</th>
      <th>Battery</th>
      <th>Column</th>
      <th>Elevator</th>
      <th>Start date intervention</th>
      <th>End date intervention</th>
      <th>Result</th>
      <th>Report</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interventions.each do |intervention| %>
      <tr>
        <td><%= intervention.author %></td>
        <td><%= intervention.customer_id %></td>
        <td><%= intervention.building_id %></td>
        <td><%= intervention.battery_id %></td>
        <td><%= intervention.column_id %></td>
        <td><%= intervention.elevator_id %></td>
        <td><%= intervention.start_date_intervention %></td>
        <td><%= intervention.end_date_intervention %></td>
        <td><%= intervention.result %></td>
        <td><%= intervention.report %></td>
        <td><%= intervention.status %></td>
        <td><%= link_to 'Show', intervention %></td>
        <td><%= link_to 'Edit', edit_intervention_path(intervention) %></td>
        <td><%= link_to 'Destroy', intervention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intervention', new_intervention_path %>

app/views/interventions/new.html.erb
<%= render 'form', intervention: @intervention %>

<%#= link_to 'Back', interventions_path %>

app/views/interventions/show.html.erb
            <!-- PAGE HEADER -->
                <section class="section-sm alternate">
                    <div class="overlay dark-4"></div>
                    <br>
                    <br>
            <h2 class="text-center">Current Intervention</h2>
                </section>
            <!-- /PAGE HEADER -->

<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @intervention.author %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @intervention.employee_id %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @intervention.customer_id %>
</p>

<p>
  <strong>Building:</strong>
  <%= @intervention.building_id %>
</p>

<p>
  <strong>Battery:</strong>
  <%= @intervention.battery_id %>
</p>

<p>
  <strong>Column:</strong>
  <%= @intervention.column_id %>
</p>

<p>
  <strong>Elevator:</strong>
  <%= @intervention.elevator_id %>
</p>

<p>
  <strong>Start date intervention:</strong>
  <%= @intervention.start_date_intervention %>
</p>

<p>
  <strong>End date intervention:</strong>
  <%= @intervention.end_date_intervention %>
</p>

<p>
  <strong>Result:</strong>
  <%= @intervention.result %>
</p>

<p>
  <strong>Report:</strong>
  <%= @intervention.report %>
</p>

<p>
  <strong>Status:</strong>
  <%= @intervention.status %>
</p>

<%= link_to 'Edit', edit_intervention_path(@intervention) %> |
<%= link_to 'Back', interventions_path %>